btre/account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'), 
    path('register/', views.register, name = 'register'),
    path('validate_username',views.validate_username, name= 'validate_username'), 
    path('dashboard/', views.dashboard, name = 'dashboard'),
]

btre/listings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'listings'), 
    path('<int:listing_id>', views.listing, name = 'listing'), 
    path('search/', views.search, name = 'search'),
    path('find/', views.find, name = 'find'),
]

btre/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
]

btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
import debug_toolbar


urlpatterns = [
    path('', include(('btre.pages.urls','pages'), namespace ='pages')),
    path('listings/', include(('btre.listings.urls','listings'), namespace ='listings')),
    path('account/', include(('btre.account.urls', 'account'), namespace ='account')),
    path('contact/', include(('btre.contact.urls','contact'), namespace ='contact')),
    path('dashboard/', include(('btre.dashboard.urls','dashboard') , namespace ='dashboard')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),	
	url(r'^static/(?P<path>.*)$', serve,{'document_root': "static"}),
    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{message.tags}} alert-dismissible text-center" role="alert">
                <button type='button' class="close" data-dismiss="alert"><span>&times;</span aria-hidden = "true"></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error
                    {% else %}
                        {{message.tags|title}}
                    {% endif %}
                </strong>
                {{message}}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
        Copyright &copy;
        <span class="year"></span> Md. Ishtiaque Hossain
    </footer>
    

templates/partials/_navbar.html
  {% load static %}

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:index' %}">
        <img src="{% static 'img/btre_logo.png' %}" class="logo" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li 
          {% if '/' == request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
          </li>
          <li 
          {% if 'about' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'pages:about'%}">About</a>
          </li>
          <li
          {% if 'listings' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'listings:listings' %}">Featured Listings</a>
          </li>
        </ul> 

        <ul class="navbar-nav ml-auto">
          
          
          {% if request.user.is_authenticated %}
            
          <li
            {% if 'dashboard' in request.path %}
            class="nav-item active mr-3"
            {% else %}
            class="nav-item mr-3"
            
            {% endif %}
            >
              <a class="nav-link" href="{% url 'account:dashboard' %}">
                <i class="fas fa-user-plus"></i>Hello {{user.username}}</a>
            </li>
            <li class="nav-item mr-3">
              <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                <i class="fas fa-sign-out-alt"></i>Logout
              </a>
              <form action="{% url 'account:logout' %}" method="post" id="logout">
                {% csrf_token %}
                <input type="hidden">
              </form>
            </li>
          
          {% else %}
            <li
            {% if 'register' in request.path %}
            class="nav-item active mr-3"
            {% else %}
            class="nav-item mr-3"
            {% endif %}
            >
              <a class="nav-link" href="{% url 'account:register' %}">
                <i class="fas fa-user-plus"></i>Register</a>
            </li>

            <li
            {% if 'login' in request.path %}
            class="nav-item active mr-3"
            {% else %}
            class="nav-item mr-3"
            {% endif %}
            >
              <a class="nav-link" href="{% url 'account:login' %}">
                <i class="fas fa-sign-in-alt"></i>Login</a>
            </li>
          {% endif %}
          </ul>
        </div>
      </div>
    </nav>

templates/partials/_topbar.html
      <!-- Top Bar -->
      <section id="top-bar" class="p-3">
        <div class="container">
          <div class="row">
            <div class="col-md-5">
              <i class="fas fa-phone"></i> (880) 1864 027978
            </div>
            <div class="col-md-5">
              <i class="fas fa-envelope-open"></i> contact@btrealestate.co
            </div>
            <div class="col-md-2">
              <div class="social text-right">
                <a href="#">
                  <i class="fab fa-twitter"></i>
                </a>
                <a href="#">
                  <i class="fab fa-facebook"></i>
                </a>
                <a href="#">
                  <i class="fab fa-linkedin"></i>
                </a>
                <a href="#">
                  <i class="fab fa-instagram"></i>
                </a>
                <a href="#">
                  <i class="fab fa-pinterest"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
    