btre/contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name = 'contact'), 
]

btre/listings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'listings'), 
    path('<int:listing_id>', views.listing, name = 'listing'), 
    path('search/', views.search, name = 'search'),
    path('find/', views.find, name = 'find'),
]

btre/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
]

btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
import debug_toolbar


urlpatterns = [
    path('', include(('btre.pages.urls','pages'), namespace ='pages')),
    path('listings/', include(('btre.listings.urls','listings'), namespace ='listings')),
    path('account/', include(('btre.account.urls', 'account'), namespace ='account')),
    path('contact/', include(('btre.contact.urls','contact'), namespace ='contact')),
    path('dashboard/', include(('btre.dashboard.urls','dashboard') , namespace ='dashboard')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),	
	url(r'^static/(?P<path>.*)$', serve,{'document_root': "static"}),
    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

btre/listings/models.py
from django.db import models
from datetime import datetime
from btre.realtors.models import Realtor

class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete = models.DO_NOTHING, blank = True,null=True)
    title = models.CharField( max_length=200, blank = True,null=True)
    description = models.TextField(blank = True, null=True)
    address = models.CharField( max_length=200, blank = True,null=True)
    city = models.CharField( max_length=100, blank = True,null=True)
    state = models.CharField( max_length=100, blank = True,null=True)
    zipcode = models.CharField( max_length=20, blank = True, null=True)
    price = models.IntegerField(blank = True, null=True)
    bedrooms = models.IntegerField(blank = True, null=True)
    garage = models.IntegerField(default=0,blank = True, null=True)
    sqft = models.IntegerField(blank = True, null=True)
    bathrooms = models.DecimalField( max_digits=2, decimal_places=1, blank = True, null=True)
    lot_size = models.DecimalField( max_digits=5, decimal_places=1, blank = True, null=True)
    list_date = models.DateField( default=datetime.now, blank = True, null=True )
    is_published = models.BooleanField(default=True, blank = True, null=True)
    photo_main = models.ImageField( upload_to='Photos/%Y/%m/%d', blank = True, null=True)
    photo1 = models.ImageField( upload_to='Photos/%Y/%m/%d', blank = True, null=True)
    photo2 = models.ImageField( upload_to='Photos/%Y/%m/%d', blank = True, null=True)
    photo3 = models.ImageField( upload_to='Photos/%Y/%m/%d', blank = True, null=True)
    photo4 = models.ImageField( upload_to='Photos/%Y/%m/%d', blank = True, null=True)
    photo5 = models.ImageField( upload_to='Photos/%Y/%m/%d', blank = True, null=True)
    photo6 = models.ImageField( upload_to='Photos/%Y/%m/%d', blank = True, null=True)
    def __str__(self):
        return self.title

btre/listings/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator

from itertools import chain
from .models import Listing
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .choices import bedroom_choices, price_choices, state_choices
from django.http import JsonResponse

def index(request):
    listings = Listing.objects.order_by('-list_date').filter(is_published=True)
    paginator = Paginator(listings, 6) # Show 3 contacts per page.
    page_number = request.GET.get('page')
    page_listings = paginator.get_page(page_number)

    context = {
        'listings' : page_listings
    }
    
    return render(request, 'listings/listings.html', context) 

def listing(request, listing_id):
    listing = get_object_or_404(Listing, pk = listing_id)
    context = {
        'listing' : listing
    }
    return render(request, 'listings/listing.html', context) 

def search(request):
    queryset_list = Listing.objects.order_by('-list_date')

    #filter for keywords
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(description__icontains = keywords) 
    
    #filter for city
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__iexact = city)
     
     #filter for state
    if 'state' in request.GET:
        state = request.GET['state']
        if state:
            queryset_list = queryset_list.filter(state__iexact = state) 

    #filter for bedrooms
    if 'bedrooms' in request.GET:
        bedrooms = request.GET['bedrooms']
        if bedrooms:
            queryset_list = queryset_list.filter(bedrooms__lte = bedrooms) 

    #filter for price
    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(price__lte = price) 

    context = {
        'listings' : queryset_list,
        'bedroom_choices' : bedroom_choices,
        'price_choices' : price_choices,
        'state_choices' : state_choices,
        'values' : request.GET
    }
    return render(request, 'listings/search.html', context)  

def find(request):
    if request.is_ajax():
        search_text = request.GET.get("search_text", "").lower()
        if len(search_text)==0:
            return JsonResponse({'listings':[]})
        startswith = Listing.objects.filter(title__istartswith=search_text)
        listings = list(chain(startswith.values_list('title', flat=True), Listing.objects.filter(title__icontains=search_text).exclude(pk__in=startswith.values_list('pk', flat=True)).values_list('title', flat=True)))
        return JsonResponse({'listings':listings})
    return render(request, 'listings/find.html')

templates/listings/find.html
{% extends 'base.html' %}

<!-- 
<input type="text"> radio checkbox file number email date password
<select name="" id=""></select>
<textarea name="" id="" cols="30" rows="10"></textarea>
form-control

<label for=""></label>
control-label -->

{% block style %}
    <style>
        #suggestion_div{
            margin-top:6px;
        }

        #suggestion_div p{
            border-bottom:solid 1px rgb(150,150,150);
        }
    </style>
{% endblock %}

{% block content %}
    <br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4 col-md-2 col-sm-12"></div>
            <div class="col-lg-4 col-md-8 col-sm-12">
                <input type="text" id="search_box" class="form-control" autocomplete="off"/>
                <div id="suggestion_div"></div>
            </div>
        </div>
    </div>
    <br><br><br><br/>
    <br><br><br><br/>
    <br><br><br><br/>
{% endblock content %}

{% block script %}
  <script>
    
    $(document).ready(function(){
        
        $("#search_box").keyup(function(){
            var search_text =  $.trim($(this).val());
            
            $.ajax({
               url:"{% url 'listings:find' %}",
               method:"GET",
               data:{
                   search_text:search_text
               },
               success:function(data){
                    if(data.listings.length==0){
                        $("#suggestion_div").html("");
                    }else{
                        var suggestion_html = "";
                        for(a_listing of data.listings){
                            suggestion_html += "<p>"+a_listing+"</p>";
                        }
                        $("#suggestion_div").html(suggestion_html);
                    }
               },
               error:function(err){
                    $("#suggestion_div").html("");
               }
            });

        });
        
    });
    

  </script>
{% endblock script %}

templates/listings/listing.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block title %} | {{listing.title}} {% endblock %}
{% block content %}

<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">{{listing.title}}</h1>
          <p class="lead">
            <i class="fas fa-map-marker"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings:listings' %}">Listings</a>
          </li>
          <li class="breadcrumb-item active">{{listing.title}}</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listing -->
  <section id="listing" class="py-4">
    <div class="container">
      {% include 'partials/_alerts.html' %}
      <a href="{% url 'listings:listings' %}" class="btn btn-light mb-4">Back To Listings</a>
      <div class="row">
        <div class="col-md-9">
          <!-- Home Main Image -->
          <img src="{{ listing.photo_main.url }}" alt="" class="img-main img-fluid mb-3">
          <!-- Thumbnails -->
          <div class="row mb-5 thumbs">

            
            {% if listing.photo1 %}
            <div class="col-md-2">
              <a href="{{ listing.photo1.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo1.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo2 %}
            <div class="col-md-2">
              <a href="{{ listing.photo2.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo2.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo3 %}
            <div class="col-md-2">
              <a href="{{ listing.photo3.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo3.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo4 %}
            <div class="col-md-2">
              <a href="{{ listing.photo4.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo4.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo5 %}
            <div class="col-md-2">
              <a href="{{ listing.photo5.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo5.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo6 %}
            <div class="col-md-2">
              <a href="{{ listing.photo6.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo6.url }}" alt="" class="img-fluid">
              </a>
            </div>
          </div>
          {% endif %}
          <!-- Fields -->
          <div class="row mb-5 fields">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-money-bill-alt"></i> Asking Price:
                  <span class="float-right">{{listing.price | intcomma}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Bedrooms:
                  <span class="float-right">{{ listing.bedrooms }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bath"></i> Bathrooms:
                  <span class="float-right">{{ listing.bathrooms }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-car"></i> Garage:
                  <span class="float-right">{{listing.garage}}
                  </span>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-th-large"></i> Square Feet:
                  <span class="float-right">{{ listing.sqft }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-square"></i> Lot Size:
                  <span class="float-right">{{listing.lot_size}} Acres
                  </span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-calendar"></i> Listing Date:
                  <span class="float-right">{{listing.list_date}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Realtor:
                  <span class="float-right">{{listing.realtor}}
                  </span>
                </li>


              </ul>
            </div>
          </div>

          <!-- Description -->
          <div class="row mb-5">
            <div class="col-md-12">
              {{listing.description}}
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3">
            <img class="card-img-top" src="{{listing.realtor.photo.url }}" alt="Seller of the Month">
            <div class="card-body">
              <h5 class="card-title">Property Realtor</h5>
              <h6 class="text-secondary">{{listing.realtor}}</h6>
            </div>
          </div>
          <button type="button" class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An Inquiry</button>
        </div>
      </div>
    </div>
  </section>

  <!-- Inquiry Modal -->
  <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{% url 'contact:contact' %}" method="POST">
            {% csrf_token %}
            
            {% if user.is_authenticated %}
              <input type="hidden" name="user_id" value="{{ user.id }}">
            {% else %}
              <input type="hidden" name="user_id" value="0">
            {% endif %}
              <input type="hidden" name="realtor_email" value="{{listing.realtor.email}}">
              <input type="hidden" name="listing_id" value="{{listing.id}}">
            <div class="form-group">
              <label for="property_name" class="col-form-label">Property:</label>
              <input type="text" name="listing" class="form-control" value="{{listing.title}}">
            </div>
            <div class="form-group">
              <label for="name" class="col-form-label">Name:</label>
              <input type="text" name="name" class="form-control" {% if user.is_authenticated %} value="{{ user.name }}" {% endif %} required>
            </div>
            <div class="form-group">
              <label for="email" class="col-form-label">Email:</label>
              <input type="email" name="email" class="form-control" {% if user.is_authenticated %} value="{{user.email}}" {% endif %} required>
            </div>
            <div class="form-group">
              <label for="phone" class="col-form-label">Phone:</label>
              <input type="text" name="phone" class="form-control">
            </div>
            <div class="form-group">
              <label for="message" class="col-form-label">Message:</label>
              <textarea name="message" class="form-control"></textarea>
            </div>
            <hr>
            <input type="submit" value="Send" class="btn btn-block btn-secondary">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/listings/listings.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} | Browse Property Listings {% endblock %}
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">Browse Our Properties</h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Browse Listings</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">

        {% if listings %}
          {% for listing in listings %}
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
              <img class="card-img-top" src="{{listing.photo_main.url}}" alt="">
              <div class="card-img-overlay">
                <h2>
                  <span class="badge badge-secondary text-white"> ${{listing.price | intcomma}} </span>
                </h2>
              </div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary"> {{listing.title}} </h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
                </div>
                <hr>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}}</div>
                  <div class="col-6">
                    <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                  <div class="col-6">
                    <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
                </div>
                <hr>
                <div class="row py-2 text-secondary">
                  <div class="col-12">
                    <i class="fas fa-user"></i> {{listing.realtor}}</div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-6">
                    <i class="fas fa-clock"></i> {{listing.list_date | timesince}}</div>
                </div>
                <hr>
                <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
              </div>
            </div>
          </div>  
          {% endfor %}

        {% else %}
          <div class="col_md_12">
            <p>No Listings Available </p>
          </div>
        {% endif %}

      </div>

      <div class="row">
        <div class="col-md-12">
          {% if listings.has_other_pages %}
            <ul class="pagination">
              {% if listings.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ listings.previous_page_number }}">&laquo;</a></li>
              {% else %}
                <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
              {% endif %}
              {% for i in listings.paginator.page_range %}
                {% if listings.number == i %}
                  <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                {% else %}
                  <li class="page-item" ><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}
              {% if listings.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ listings.next_page_number }}">&raquo;</a></li>
              {% else %}
                <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
              {% endif %}
            </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/listings/search.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} | Search Property {% endblock %}
{% block content %}
<section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <form action="{% url 'listings:search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Keywords</label>
                <input type="text" name="keywords" class="form-control" placeholder="Keyword (Pool, Garage, etc)" value="{{ values.keywords }}">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">City</label>
                <input type="text" name="city" class="form-control" placeholder="City" value="{{values.city}}">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">State</label>
                <select name="state" class="form-control">
                  <option selected="true" disabled="disabled">State (All)</option>
                    {% for key,value in state_choices.items %}
                      <option value="{{key}}"
                      {% if key == values.state %}
                        selected                        
                      {% endif %}
                      >{{value}}</option>
                    {% endfor %} 
                </select>
              </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">Bedrooms</label>
                <select name="bedrooms" class="form-control">
                  <option selected="true" disabled="disabled">Bedrooms (Any)</option>
                  {% for key,value in bedroom_choices.items %}
                      <option value="{{key}}"
                      {% if key == values.bedrooms %}
                        selected                        
                      {% endif %}
                      >{{value}}</option>
                    {% endfor %}
                </select>
              </div>
              <div class="col-md-6 mb-3">
                <select name="price" class="form-control">
                  <option selected="true" disabled="disabled">Max Price (All)</option>
                  {% for key,value in price_choices.items %}
                      <option value="{{key}}"
                      {% if key == values.price %}
                        selected                        
                      {% endif %}
                      >{{value}}</option>
                    {% endfor %}
                </select>
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
          </form> 
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings:listings' %}">Browse Listings</a>
          </li>
          <li class="breadcrumb-item active"> Search Results</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">

        {% if listings %}
          {% for listing in listings %}
            <div class="col-md-6 col-lg-4 mb-4">
              <div class="card listing-preview">
                <img class="card-img-top" src="{{listing.photo_main.url}}" alt="">
                <div class="card-img-overlay">
                  <h2>
                    <span class="badge badge-secondary text-white">{{ listing.price | intcomma }}</span>
                  </h2>
                </div>
                <div class="card-body">
                  <div class="listing-heading text-center">
                    <h4 class="text-primary">{{ listing.title }}</h4>
                    <p>
                      <i class="fas fa-map-marker text-secondary"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
                  </div>
                  <hr>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}}</div>
                    <div class="col-6">
                      <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
                  </div>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                    <div class="col-6">
                      <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
                  </div>
                  <hr>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-user"></i> {{listing.realtor}}</div>
                  </div>
                  <div class="row text-secondary pb-2">
                    <div class="col-6">
                      <i class="fas fa-clock"></i> {{listing.list_date | timesince}}</div>
                  </div>
                  <hr>
                  <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                </div>
              </div>
            </div>
          {% endfor %}
        
        {% else %}
            <div class="col_md_12">
              <p>No Listings Available</p>
            </div>
        {% endif %}  

      </div>
    </div>
  </section>

{% endblock %}