btre/account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'), 
    path('register/', views.register, name = 'register'),
    path('validate_username',views.validate_username, name= 'validate_username'), 
    path('dashboard/', views.dashboard, name = 'dashboard'),
]

btre/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path("dashboard/", views.dashboard, name="dashboard"),
    path('viewuser/<int:user_id>', views.viewuser, name='viewuser'),
    path('edituser/<int:user_id>', views.edituser, name='edituser'),
    path('updateuser/<int:user_id>', views.updateuser, name = 'updateuser'),
    path('deleteuser/<int:user_id>', views.deleteuser, name='deleteuser'),

]

btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
import debug_toolbar


urlpatterns = [
    path('', include(('btre.pages.urls','pages'), namespace ='pages')),
    path('listings/', include(('btre.listings.urls','listings'), namespace ='listings')),
    path('account/', include(('btre.account.urls', 'account'), namespace ='account')),
    path('contact/', include(('btre.contact.urls','contact'), namespace ='contact')),
    path('dashboard/', include(('btre.dashboard.urls','dashboard') , namespace ='dashboard')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),	
	url(r'^static/(?P<path>.*)$', serve,{'document_root': "static"}),
    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

btre/dashboard/models.py
from django.db import models

# Create your models here.

btre/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib.auth.hashers import make_password
from .decorators import login_required, superuser_required, staff_required

# Create your views here.
@superuser_required
def index(request):
    
    return render(request, 'dashboard/index.html')

@login_required
def dashboard(request):
    if not request.user.is_superuser and not request.user.is_staff:
        return redirect('account:dashboard')
    users = User.objects.all()
    user = request.user
    context = {
        'users': users,
        'user' : user
        }              
    return render(request, 'dashboard/dashboard.html', context)

@superuser_required
def viewuser(request, user_id):
    try:
        #user_details = get_object_or_404(User, pk = user_id)
        user_details = User.objects.get(pk=user_id)
        context = {
                'user_details': user_details
            }
        return render(request, 'dashboard/viewuser.html', context)
    except:
        return render(request, 'dashboard/404.html')

@superuser_required
def edituser(request, user_id):
    try:
        print(user_id)
        #user_details = get_object_or_404(User, pk = user_id)
        user_details = User.objects.get(pk=user_id)
        context = {
                'user_details': user_details
            }
        return render(request, 'dashboard/edituser.html', context)
    except Exception as e:
        print(e)
        return render(request, 'dashboard/404.html')

@superuser_required
def updateuser(request, user_id):
    if request.is_ajax and request.method == 'POST':
        #Get form values
        request.POST.get("csrfmiddlewaretoken")
        first_name = request.POST.get("first_name","")
        last_name = request.POST.get("last_name","")
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        is_superuser = (request.POST.get("is_superuser", "0") == "1")
        #is_superuser = False
        #if (request.POST.get("is_superuser", "0") == "1"):
            #is_superuser = True
        is_staff = (request.POST.get("is_staff","0") == "1")
        #print(is_staff)

        #check if username matches 
        
        
        if User.objects.filter(username__iexact = username ).exclude( pk = user_id ).exists():
            data = {
                'status': 1
                #alert user exists
            }
            return JsonResponse(data)
            #return redirect('register')
        #check if email matches
        if User.objects.filter( email = email ).exclude( pk=user_id ).exists():
            data = {
                'status': 2
                #alert email exists
            }
            return JsonResponse(data)
        if len(password)!=0 and len(password)<6:
            pass
        user = User.objects.get(pk=user_id)
        user.username = username
        user.email = email
        if len(password)!=0:
            user.password = make_password(password)
        user.first_name = first_name
        user.last_name = last_name
        user.is_superuser = is_superuser
        user.is_staff = is_staff
        user.save()
        data = {
        'status': 3 
        #alert user is saved
        }  
        return JsonResponse(data)
    try: 
        user_details = User.objects.get( pk = user_id )
        context = {
            'user_details': user_details
        }              
        return render(request, 'dashboard/edituser.html', context)
    except:
        return render(request, 'dashboard/404.html')

@superuser_required
def deleteuser(request, user_id):
    if request.is_ajax and request.method == 'POST':
        try:
            #user_details = get_object_or_404(User, pk = user_id)
            user_details = User.objects.get(pk=user_id)
            user_details.delete()
            data = {
                'status':1
            }
            return JsonResponse(data)
        except:
            return render(request, 'dashboard/404.html')
    else:
        users = User.objects.all()
        context = {
            'users': users
        }              
        return render(request, 'dashboard/dashboard.html', context) 

templates/dashboard/dashboard.html
{% extends "base.html" %}

{% block title %} | User Dashboard {% endblock %}
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container"> 
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">Admin Dashboard</h1>
          <p class="lead">Manage your Users </p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'account:login' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Dashboard</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="dashboard" class="py-4">    
    <div class="container">
      <h2>Welcome {{ user.username }} </h2>
      <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4><i class="fas fa-user-plus"></i> View User</h4>
            </div>
            <div class="card-body">
            <table class="table">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              
              {% if users %}
                {% for user in users %}
                  <tr data-id="{{user.id}}">
                    <td>{{ user.username }}</td>
                    <td><a class="btn btn-primary" style="background-color: #30caa0; border-color: #30caa0;" href="{% url 'dashboard:viewuser' user.id %}">View</a></td>
                    <td><a class="btn btn-primary" style="background-color: #30caa0; border-color: #30caa0;" href="{% url 'dashboard:edituser' user.id %}">Edit</a></td>
                    <td><button class="btn btn-danger deletebutton" data-id="{{user.id}}" data-url="{% url 'dashboard:deleteuser' user.id %}">Delete</button></td>
                  </tr>
                {% endfor %}
              {% endif %}
              
            </tbody>
          </table>
            </div>
          </div>
        </div>
      

        <div class="col-lg-6 col-md-12 col-sm-12">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4><i class="fas fa-user-plus"></i> Add User</h4>
            </div>
            <div class="card-body">                
                  <div class="form-group">
                  <label for="first_name">First Name:</label>
                  <input type="text" id="first_name" name="first_name" class="form-control">
                </div>
                <div class="form-group">
                  <label for="last_name">Last Name:</label>
                  <input type="text" id="last_name" name="last_name" class="form-control">
                </div>
                <div class="form-group">
                  <label for="username">Username:</label>
                  <input type="text" id="username" name="username" class="form-control">
                </div>
                <div class="form-group">
                  <label for="email">Email:</label>
                  <input type="email" id="email" name="email" class="form-control">
                </div>
                <div class="form-group">
                  <label for="password">Password:</label>
                  <input type="password" placeholder="Must contain 6 characters" id="password" name="password" class="form-control">
                </div>  
                <div class="form-group">
                  <label for="is_superuser">Is a superuser? :</label>
                  <input type="checkbox" id="is_superuser" >  
                </div>
                <div class="form-group">
                  <label for="is_staff">Is a staff? :</label>
                  <input type="checkbox" id="is_staff">
                </div>
               
                <button id="save-button" class="btn btn-secondary btn-block">
                  Save
                </button>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

{% block script %}
<script>

$(document).ready(function(){


  $("#username, #email").keyup(function(){
    $(this).val($.trim($(this).val()).toLowerCase());
    
  });

  $("#save-button").click(function(){
    var first_name = $("#first_name").val();
    var last_name = $("#last_name").val();
    var username = $.trim($("#username").val());
    var password = $("#password").val();
    var email = $.trim($("#email").val());
    var is_superuser = $("#is_superuser").is(":checked") ? 1:0;
    var is_staff = $("#is_staff").is(":checked") ? 1:0;
    //console.log(email)
    //console.log(is_staff)

      if(username.length == 0){
        //alert("username is required");
        $.alert({
          title: 'Alert!',
          content: 'Username is required!',
      });
        //$('#username').focus();
        return;
      }

      if(email.length == 0){
        //alert("email is required");
        //$('#email').focus();
        $.alert({
          title: 'Alert!',
          content: 'Email is required!',
      });
        return;
      }

      if(password.length == 0){
        //alert("password is required");
        //$('#pasword').focus();
        $.alert({
          title: 'Alert!',
          content: 'Password is required!',
      });
        return;
      }

      if(password.length < 6){
        //alert("password must be at least 6 characters");
        //$('#password').focus();
        $.alert({
          title: 'Alert!',
          content: 'password must be at least 6 characters!',
      });
        return;
      }
      
      if(/^[A-Za-z0-9_]+$/.test(username) == false){
        //alert("Username only contains characters, numbers and underscores")
        //$('#username').focus();
        $.alert({
          title: 'Alert!',
          content: 'Username only contains characters, numbers and underscores!',
      });
        return;
      }

      if(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(email) == false){
        //alert("Invalid email");
        //$('#email').focus();
        $.alert({
          title: 'Alert!',
          content: 'Invalid email!',
      });
        return;
      }
      
      
      $.ajax({
        url:"{% url 'account:register' %}",
        method:"POST",
        data:{username:username, password:password, email:email, first_name:first_name, last_name:last_name, is_superuser:is_superuser, is_staff:is_staff, csrfmiddlewaretoken:"{{csrf_token}}"},
        success:function(response){
            if(response.status == 1){
              //console.log("ok");
              //alert("");
              $.alert({
                title: 'Alert!',
                content: 'This user exists!',
            });
              //window.location.href = location.href;
              //$("#username").focus();
            }
            else if(response.status == 2){
              //alert("");
              $.alert({
                title: 'Alert!',
                content: 'email already exists!',
            });
              //window.location.href = location.href;
              //$("#email").focus();
            }
            else if(response.status == 3){
              //alert("User is saved successfully");
              $.alert({
                title: 'Congratulations!',
                content: 'User is saved successfully!',
              });
              setTimeout(function(){
                window.location.href = "{% url 'dashboard:dashboard' %}"
              },1000);
            }
            else{
              $.alert({
                  title: 'Alert!',
                  content: 'Sorry, an error occured!',
              });
            }
        },
        error:function(err, ajaxOptions, thrownError){
          $.alert({
            title: 'Alert!',
            content: "Save failed- please try again later!",
          });
          //alert('Save failed - please try again');
        }
    });
  });

  $(".deletebutton").click(function(e){
    //e.preventDefault();
    var user_url = $.trim($(this).data("url"));
    //var user_delete = $(this).closest( 'tr');
    var user_id = $.trim($(this).data("id"));

    $.confirm({
      icon: 'fa fa-question',
      title: 'Delete!',
      content: 'Are you sure to continue?',
      type: 'red',
      typeAnimated: true,
      closeIcon: true,
      closeIconClass: 'fa fa-close',
      escapeKey: true,
      backgroundDismiss: true,
      buttons: {
          tryAgain: {
              text: 'Confirm',
              btnClass: 'btn-red',
              action: function(){
                $.ajax({
                  
                  url: user_url,
                  method:"POST",
                  data: {csrfmiddlewaretoken:"{{csrf_token}}"},
                  success: function(response){
                    if(response.status == 1){
                      //user_delete.remove();
                      $('tr[data-id="'+user_id+'"]').remove();
                      $.alert({
                        title: 'Congratulations!',
                        content: 'User is deleted successfully!',  
                    });
                    }
                  },
                  error: function(err, ajaxOptions, thrownError){
                    alert('Delete failed - please try again');
                  },
                    });
              }
          },
          close: {
            text: 'Cancel',
            action: function () {
 
          },
        }
      },


    });

  });
});


</script>
{% endblock %}

templates/dashboard/edituser.html
{% extends 'base.html' %}

{% block title %} | {{ user_details.username}}{% endblock %}

{% block content %}

<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">{{user_details.username}}</h1>
          <p class="lead">
            <i class="fas fa-map-marker"></i> {{user_details.email}}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">{{user_details.username}}</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="edituser" class="py-4">    
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-user-plus"></i> Edit User</h4>
              </div>
              <div class="card-body">                
                    <div class="form-group">
                    <label for="first_name">First Name:</label>
                    <input type="text" id="first_name" name="first_name" class="form-control" value="{{user_details.first_name}}" >
                  </div>
                  <div class="form-group">
                    <label for="last_name">Last Name:</label>
                    <input type="text" id="last_name" name="last_name" class="form-control" value="{{user_details.last_name}}">
                  </div>
                  <div class="form-group">
                    <label for="username">Username:</label>
                    <input type="text" id="username" name="username" class="form-control" value="{{user_details.username}}">
                  </div>
                  <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control"  value="{{user_details.email}}">
                  </div>
                  <div class="form-group">
                    <label for="password2">Password:</label>
                    <input type="password" placeholder="Must contain 6 characters" id="password" name="password" class="form-control">
                  </div>  
                  <div class="form-group">
                    <label for="is_superuser">Is a superuser? :</label>
                    <input type="checkbox" id="is_superuser" {% if user_details.is_superuser %}checked{% endif %} >  
                  </div>
                  <div class="form-group">
                    <label for="is_staff">Is a staff? :</label>
                    <input type="checkbox" id="is_staff" {% if user_details.is_staff %}checked{% endif %}>
                  </div>
                 
                  <button id="update-button" class="btn btn-secondary btn-block">
                    Update
                  </button>
                
              </div>
            </div>
          </div>
      </div>
    </div>
  </section>
    
{% endblock %}


{% block script %}
<script>

$(document).ready(function(){


  $("#username, #email").keyup(function(){
    $(this).val($.trim($(this).val()).toLowerCase());
    
  });

  $("#update-button").click(function(){
    var first_name = $("#first_name").val();
    var last_name = $("#last_name").val();
    var username = $.trim($("#username").val());
    var password = $("#password").val();
    var email = $.trim($("#email").val());
    var is_superuser = $("#is_superuser").is(":checked") ? 1:0;
    var is_staff = $("#is_staff").is(":checked") ? 1:0;
    //console.log(email)
    //console.log(is_staff)

      if(username.length == 0){
        //alert("");
        $.alert({
          title: 'Alert!',
          content: 'Username is required!',
      });
        return;
      }

      if(password.length != 0 && password.length < 6){
        //alert("");
        $.alert({
          title: 'Alert!',
          content: 'Password must be at least 6 characters!',
      });
        return;
      }

      if(email.length == 0){
        //alert("");
        $.alert({
          title: 'Alert!',
          content: 'Email is required!',
      });
        return;
      }
      
      if(/^[A-Za-z0-9_]+$/.test(username) == false){
        //alert("")
        $.alert({
          title: 'Alert!',
          content: 'Username only contains characters, numbers and underscores!',
      });
        return;
      }

      if(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(email) == false){
        //alert("");
        $.alert({
          title: 'Alert!',
          content: 'Invalid email!',
      });
        return;
      }
      
      
      $.ajax({
        url:"{% url 'dashboard:updateuser' user_details.id %}",
        method:"POST",
        data:{username:username, password:password, email:email, first_name:first_name, last_name:last_name, is_superuser:is_superuser, is_staff:is_staff, csrfmiddlewaretoken:"{{csrf_token}}"},
        success:function(response){
            if(response.status == 1){
              //alert("");
              //$("#username").val("");
              $.alert({
                title: 'Alert!',
                content: 'This user exists!',
            });
            }
            else if(response.status == 2){
              //alert("");
              //$("#email").val("");
              $.alert({
                title: 'Alert!',
                content: 'This user exists!',
            });
            }
            else{
              //alert("");
              $.alert({
                title: 'Alert!',
                content: 'User is updated successfully!',
            });
            setTimeout(function(){
              window.location.href = "{% url 'dashboard:viewuser' user_details.id %}"},
              1000);
            }
        },
        error:function(err, ajaxOptions, thrownError){
          alert('Update failed - please try again');
        }
    });
  });

});


</script>

{% endblock %}

templates/dashboard/index.html
{% extends 'dashboard/dashboard_base.html' %}

{% block title %} | Dashboard {% endblock %}

{% block style %}
	<style>
		h1{
			font-family:'Titillium Web', sans-serif;
		}
		.statistics_parent{
			text-align:center;
			margin-top:30px;
			padding:16px 6px;
			border-radius:3px;
			border-top:solid 3px #2ea281;
			box-shadow:0px 1px 3px #57987d;
		}
		.statistics_parent h1{
			color:black;
			font-size:3em;
		}
		.statistics_parent span{
			color:black;
			font-size:1.15em;
		}
		.statistics_parent span .fa{
			color:#32a47d;
			font-size:1.3em;
		}
		.statistics_parent span .fas{
			color:#32a47d;
			font-size:1.16em;
		}
	</style>
{% endblock %}

{% block main_content %}
	
	<br/><br/>
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<h1>Summary</h1>
			</div>
			{% if request.user.is_superuser %}
				<div class="col-lg-3 col-md-2 col-sm-12">
					<div class="statistics_parent">
						<h1>{{product_type_count}}</h1>
						<span><i class="fas fa-list"></i> &nbsp;Total Product Types</span>
					</div>
				</div>
				<div class="col-lg-3 col-md-2 col-sm-12">
					<div class="statistics_parent">
						<h1>{{categories}}</h1>
						<span><i class="fas fa-list-alt"></i> &nbsp;Categories</span>
					</div>
				</div>
				<div class="col-lg-3 col-md-2 col-sm-12">
					<div class="statistics_parent">
						<h1>{{brands}}</h1>
						<span><i class="fas fa-handshake"></i> &nbsp;Brands</span>
					</div>
				</div>
				<div class="col-lg-3 col-md-2 col-sm-12">
					<div class="statistics_parent">
						<h1>{{products}}</h1>
						<span><i class="fas fa-credit-card"></i> &nbsp;Products</span>
					</div>
				</div>
				<div class="col-lg-3 col-md-2 col-sm-12">
					<div class="statistics_parent">
						<h1>{{verified_users}}</h1>
						<span><i class="fas fa-users"></i> &nbsp;Verified Users</span>
					</div>
				</div>
			{% endif %}
			<div class="col-lg-3 col-md-2 col-sm-12">
				<div class="statistics_parent">
					<h1>{{orders}}</h1>
					<span>
						<i class="fa fa-cogs"></i> &nbsp;Total Orders
						{% if not request.user.is_superuser %}
							<br/>by me
						{% endif %}
					</span>
				</div>
			</div>
			<div class="col-lg-3 col-md-2 col-sm-12">
				<div class="statistics_parent">
					<h1>{{confirmed}}</h1>
					<span>
						<i class="fa fa-check-square-o"></i> &nbsp;Confirmed Orders
						{% if not request.user.is_superuser %}
							<br/>by me
						{% endif %}
					</span>
				</div>
			</div>
			<div class="col-lg-3 col-md-2 col-sm-12">
				<div class="statistics_parent">
					<h1>{{delivered}}</h1>
					<span>
						<i class="fa fa-handshake-o"></i> &nbsp;Delivered Orders
						{% if not request.user.is_superuser %}
							<br/>by me
						{% endif %}
					</span>
				</div>
			</div>
		</div>
	</div>
	
{% endblock %}

{% block script %}
	<script>
		
		$(document).ready(function(){
		
			$('.nav-dashboard[data-menu="dashboard"]').addClass("active");
			
		});
		
	</script>
{% endblock %}

templates/dashboard/viewuser.html
{% extends 'base.html' %}

{% block title %} | {{ user_details.username}}{% endblock %}

{% block content %}

<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">{{user_details.username}}</h1>
          <p class="lead">
            <i class="fas fa-map-marker"></i> {{user_details.email}}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">{{user_details.username}}</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="viewuser" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          
          <table class="table">
            <thead>
              <tr>
                <th scope="col">id</th>
                <th scope="col">Name</th>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Is a superuser?</th>
                <th scope="col">Is a staff?</th>
              </tr>
            </thead>
            <tbody>
            
            {% if user_details %}
                
                    <tr>
                    <td> {{user_details.id}} </td>
                    <td> {{user_details.first_name }} {{user_details.last_name}} </td>
                    <td> {{user_details.username}} </td>
                    <td> {{user_details.email}} </td>
                    <td>{{user_details.is_superuser}}</td>
                    <td>{{user_details.is_staff}}</td>
                    </tr>
                
            {% endif %}
                
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>

{% endblock %}